./replace.sh ComplexSinCos
./replace.sh ComplexSquareRoot
./replace.sh doppler1
./replace.sh doppler2
./replace.sh doppler3
./replace.sh exp1x_log
./replace.sh i4
./replace.sh i6
./replace.sh intro_example
./replace.sh logexp
./replace.sh NMSEexample310
./replace.sh NMSEexample31
./replace.sh NMSEexample33
./replace.sh NMSEexample34
./replace.sh NMSEexample35
./replace.sh NMSEexample36
./replace.sh NMSEexample37
./replace.sh NMSEexample38
./replace.sh NMSEexample39
./replace.sh NMSEproblem331
./replace.sh NMSEproblem332
./replace.sh NMSEproblem333
./replace.sh NMSEproblem335
./replace.sh NMSEproblem336
./replace.sh NMSEproblem337
./replace.sh NMSEproblem341
./replace.sh NMSEproblem343
./replace.sh NMSEproblem344
./replace.sh NMSEsection311
./replace.sh NMSEsection35
./replace.sh polarToCarthesianX
./replace.sh predatorPrey
./replace.sh sine
./replace.sh sineorder3
./replace.sh sqroot
./replace.sh sqrt_add
./replace.sh test05_nonlin1_r4
./replace.sh test05_nonlin1_test2
./replace.sh verhulst
